// IMPORT TO AUTHREDUCER
export const SET_USER = "SET_USER";


// IMPORT TO THEMEREDUCER
export const SET_THEME = "SET_THEME";


// IMPORT TO CURRENTQUESTIONREDUCER 
// GO TO THE NEXT & !NEXT QUESTION
export const NEXT_QUESTION = "NEXT_QUESTION";
export const BACK_QUESTION = "BACK_QUESTION";


export const UPDATE_CURRENT_QUESTION = "UPDATE_CURRENT_QUESTION";
export const SUBMIT_ANSWER = "SUBMIT_ANSWER";


export const CHECK_FOR_REQUIRE_VALIDATE = "CHECK_FOR_REQUIRE_VALIDATE";
export const SET_REQUIRE_VALIDATE = "SET_REQUIRE_VALIDATE";