// IMPORT TO AUTHREDUCER
export const SET_USER = "SET_USER";


// IMPORT TO THEMEREDUCER
export const SET_THEME = "SET_THEME";


// IMPORT TO CURRENTQUESTIONREDUCER 
// GO TO THE NEXT & !NEXT QUESTION
export const NEXT_QUESTION = "NEXT_QUESTION";
export const BACK_QUESTION = "BACK_QUESTION";